Webinars Component Added
sliit-foss/sliitfoss pull request #173
Opened 2021-01-30 18:15 UTC by Safnaj

- Webinars Component Added in Home Page
- Webinars Component Added in Events Page
- Footer Modified

Button in the Cards misplaced. Need to be corrected with CSS

2021-01-30 19:44 UTC, Bawanthathilan approved these changes

2021-01-30 20:29 UTC, Shehanka requested changes

2021-01-30 20:29 UTC, Shehanka commented on src/app/components/common/footer/footer.component.html
> +              Copyright &copy; 2021 | All Right Reserved
Where's function that I wrote @Bawanthathilan

2021-01-30 20:29 UTC, Shehanka commented on src/app/components/past-events/past-events.component.css
> +  width: 180px;
use rem or em

2021-01-30 20:29 UTC, Shehanka commented on src/app/components/about/about.component.html
> +          =======
This still contains a conflicts stuff @Safnaj

2021-01-31 09:38 UTC, Shehanka approved these changes

2021-01-31 09:42 UTC, Bawanthathilan approved these changes

2021-01-31 09:42 UTC, merged