[Fixes] Added few fixes on blog layout and design. Removed pagination
sliit-foss/sliitfoss pull request #303
Opened 2021-10-03 16:01 UTC by banujan6

- Added few fixes on blog layout and design.
- Removed pagination

2021-10-03 16:03 UTC, Shehanka requested changes

2021-10-03 16:03 UTC, Shehanka commented on src/app/components/blog/blog.component.html
> +        <!-- <img alt="image" class="card-img w-100" src="{{ post.thumbnail }}" /> -->
remove this commented code

2021-10-03 17:22 UTC, banujan6 commented on src/app/components/blog/blog.component.html
> +        <!-- <img alt="image" class="card-img w-100" src="{{ post.thumbnail }}" /> -->
Removed

2021-10-04 02:58 UTC, Shehanka approved these changes
Thanks for contributing @banujan6 
@Bawanthathilan can u do css review too

2021-10-04 04:17 UTC, Bawanthathilan approved these changes

2021-10-04 12:17 UTC, merged