Hotfix/build script
sliit-foss/sliitfoss pull request #329
Opened 2022-02-26 19:29 UTC by Akalanka47000

2022-02-26 20:03 UTC, nisalrenuja approved these changes

2022-02-27 06:40 UTC, Shehanka approved these changes

2022-02-27 06:40 UTC, Shehanka commented on .github/workflows/firebase.yml
>            node-version: '10.x'
change node version to `16.0`

2022-02-27 06:42 UTC, Shehanka requested changes
do above requested changes

2022-02-27 06:45 UTC, Akalanka47000 commented
> do above requested changes

Updated to version 16

2022-02-27 07:28 UTC, Shehanka approved these changes

2022-02-27 08:06 UTC, merged