Add details
sliit-foss/sliitfoss pull request #82
Opened 2021-01-01 05:40 UTC by ebonynon

Update board details

2021-01-01 06:46 UTC, Safnaj requested changes

2021-01-01 06:46 UTC, Safnaj commented on src/assets/data/board.json
> +      "id": 3,
Make ur id as 10

2021-01-01 07:33 UTC, Shehanka commented
Fetch images from GitHub profile. Like we did on GC Sri Lanka @Safnaj

2021-01-01 07:34 UTC, Shehanka approved these changes

2021-01-01 07:38 UTC, Safnaj commented
> Fetch images from GitHub profile. Like we did on GC Sri Lanka @Safnaj 

If we changed GitHub profile in future it will be a issue. Better to have separate images for this.

2021-01-02 06:41 UTC, Shehanka commented
> > Fetch images from GitHub profile. Like we did on GC Sri Lanka @Safnaj
> 
> If we changed GitHub profile in future it will be a issue. Better to have separate images for this.

noo if we change it automatically picture will update

2021-01-02 06:47 UTC, Safnaj commented
> > > Fetch images from GitHub profile. Like we did on GC Sri Lanka @Safnaj
> > 
> > 
> > If we changed GitHub profile in future it will be a issue. Better to have separate images for this.
> 
> noo if we change it automatically picture will update

are you sure ?? i faced same issue when using github profile picture URL. Also we had same problem in GitHub Community Site

2021-01-02 13:58 UTC, Shehanka approved these changes

2021-01-02 13:58 UTC, merged